CREATE TABLE hotels (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hotel_id VARCHAR(20) UNIQUE NOT NULL,
    hotel_name VARCHAR(255) NOT NULL,
    city VARCHAR(100),
    country VARCHAR(100),
    star_rating INT CHECK (star_rating BETWEEN 1 AND 5) DEFAULT NULL,
    total_rooms INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
